name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install WebkitGTK development files
      run: sudo apt-get install -y libwebkit2gtk-4.1-dev xvfb
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --features webkitgtk
    - name: Run tests
      run: RUST_BACKTRACE=full RUST_LOG=debug xvfb-run cargo test --verbose --features webkitgtk