name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install WebkitGTK development files
      run: sudo apt-get install -y libwebkit2gtk-4.1-dev mingw-w64 xvfb
    - name: Add x86_64-pc-windows-gnu target
      run: rustup target add x86_64-pc-windows-gnu
    - uses: actions/checkout@v3
    - name: Build with WebkitGTK
      run: cargo build --release --verbose --features webkitgtk
    - name: Build with WebkitGTK (threadsafe)
      run: cargo build --release --verbose --features webkitgtk,threadsafe
    - name: Build with Edge WebView2 (MinGW)
      run: cargo build --release --verbose --features edge2 --target=x86_64-pc-windows-gnu
    - name: Run tests
      run: RUST_BACKTRACE=full RUST_LOG=debug xvfb-run cargo test --verbose --features webkitgtk

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/checkout@v3
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --features edge2
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features edge2
